# Generated by Django 3.2.7 on 2023-09-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('login_records', '0002_auto_20230905_1411'), ('login_records', '0003_auto_20230911_0938')]

    dependencies = [
        ('login_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='host',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='service',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='LoginLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_records.location')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_records.loginrecord')),
            ],
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='locations',
            field=models.ManyToManyField(through='login_records.LoginLocation', to='login_records.Location'),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='result',
            field=models.CharField(blank=True, default='success', max_length=64),
        ),
    ]
