# Generated by Django 2.2.7 on 2021-01-17 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openacct', '0002_default_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagecommitment',
            name='registered',
        ),
        migrations.AddField(
            model_name='job',
            name='account',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagecommitment',
            name='allocated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagecommitment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprojectevent',
            name='event_type',
            field=models.CharField(choices=[('NEWPI', 'NEWPI'), ('ADDED', 'ADDED'), ('REMOVED', 'REMOVED')], max_length=16),
        ),
    ]
