# Generated by Django 3.2.3 on 2022-12-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openacct', '0004_project_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='openacct.project'),
        ),
        migrations.AlterField(
            model_name='userprojectevent',
            name='event_type',
            field=models.CharField(choices=[('NEWPI', 'New PI'), ('ADDMGR', 'Add Manager'), ('REMOVEMGR', 'Remove Manager'), ('ADDMEM', 'Add Member'), ('REMOVEMEM', 'Remove Member')], max_length=16),
        ),
    ]
