# Generated by Django 3.2.3 on 2023-02-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openacct', '0005_project_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cluster',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='partition',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='submitter',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='tres_allocated',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='tres_requested',
            field=models.TextField(blank=True, default=''),
        ),
    ]
