# Generated by Django 3.2.3 on 2023-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openacct', '0006_additional_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='wall_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
