# Generated by Django 3.2.3 on 2023-05-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvmodulesCommandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(db_index=True)),
                ('host', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=32)),
                ('uuid', models.CharField(db_index=True, max_length=128)),
                ('command', models.CharField(max_length=1024)),
                ('jobid', models.CharField(blank=True, max_length=32, null=True)),
                ('account', models.CharField(blank=True, max_length=64, null=True)),
                ('cluster', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'envmodules_command_record',
            },
        ),
        migrations.CreateModel(
            name='EnvmodulesEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('l', 'Load'), ('u', 'Unload')], max_length=2)),
                ('auto', models.BooleanField(blank=True, default=False)),
                ('module', models.CharField(max_length=256)),
                ('caused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envmodules_records.envmodulescommandrecord')),
            ],
            options={
                'db_table': 'envmodules_event_record',
            },
        ),
    ]
